version: '3'
services:
  python-ai:
    build: .
    container_name: python-ai-server
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["python", "main.py"]